### ISSUE TITLE
소스 파일 누락

### ISSUE THREAD

**Issue by god-soo** [tonykang22/hello-world-auto-store#244]
안녕하세요.  저도 비슷한 걸 만들어보려고 search 하다가 이 저장소를 발견하였습니다.
order-manager의 com.github.kingwaggs.ordermanager.domain.sheet.QOrder. java 
product-manager의 com.github.kingwaggs.productmanager.common.domain.product.QHelloWorldAutoStoreProduct.java 

위 두개의 파일이 빠져있는데 올려주실수 있을까요?

**Comment by tonykang22** [comment]
죄송합니다. 해당 repository는 공유 목적이 아니라 소개 목적이라 파일 공유는 어렵습니다.
해당 이슈도 닫도록 하겠습니다. 관심가져주셔서 감사합니다.
